[package]
name = "pallet-transfer-allowlist"
description = "Pallet for determining whether a transfer should be allowed based of sender, receiver, and currency."
version = "0.1.0"
authors = ["Centrifuge <admin@centrifuge.io>"]
homepage = 'https://centrifuge.io'
license = "LGPL-3.0"
repository = 'https://github.com/centrifuge/centrifuge-chain'
edition = "2021"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
serde = { version = "1.0.119" }

cfg-traits = { path = "../../libs/traits", default-features = false }

cfg-types = { path = "../../libs/types", default-features = false }

frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-balances = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[dev-dependencies]
pallet-balances = { workspace = true }
sp-io = { workspace = true }

[features]
default = ['std']
runtime-benchmarks = [
  'cfg-traits/runtime-benchmarks',
  'cfg-types/runtime-benchmarks',
  'frame-benchmarking/runtime-benchmarks',
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  'pallet-balances/runtime-benchmarks',
  'sp-runtime/runtime-benchmarks',
]
std = [
  'cfg-traits/std',
  'cfg-types/std',
  "parity-scale-codec/std",
  "frame-benchmarking/std",
  'frame-support/std',
  'frame-system/std',
  'scale-info/std',
  'serde/std',
  'sp-core/std',
  'sp-runtime/std',
  'sp-std/std',
]
try-runtime = [
  'cfg-traits/try-runtime',
  'cfg-types/try-runtime',
  'frame-support/try-runtime',
  'frame-support/try-runtime',
  'frame-system/try-runtime',
  'sp-runtime/try-runtime',
]
