[package]
name = "pallet-transfer-allowlist"
description = "Pallet for determining whether a transfer should be allowed based of sender, receiver, and currency."
version = "0.1.0"
authors = ["Centrifuge <admin@centrifuge.io>"]
homepage = 'https://centrifuge.io'
license = "LGPL-3.0"
repository = 'https://github.com/centrifuge/centrifuge-chain'
edition = "2021"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0', features = ['derive'], default-features = false }
scale-info = { version = "2.3.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.119" }

cfg-traits = { path = "../../libs/traits", default-features = false }

cfg-types = { path = "../../libs/types", default-features = false }

frame-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true, branch = "polkadot-v0.9.43" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.43" }

[dev-dependencies]
cfg-mocks = { path = "../../libs/mocks" }
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = true, branch = "polkadot-v0.9.43" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = true, branch = "polkadot-v0.9.43" }

[features]
default = ['std']
runtime-benchmarks = [
  'frame-benchmarking/runtime-benchmarks',
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  'sp-runtime/runtime-benchmarks',
  'cfg-types/runtime-benchmarks',
  'cfg-traits/runtime-benchmarks',
  'cfg-mocks/runtime-benchmarks',
  'pallet-balances/runtime-benchmarks',
]
std = [
  'codec/std',
  'scale-info/std',
  'frame-support/std',
  'frame-system/std',
  "frame-benchmarking/std",
  'sp-runtime/std',
  'sp-std/std',
  'cfg-types/std',
  'cfg-traits/std',
  'serde/std',
  'sp-core/std',
]
try-runtime = [
  'frame-support/try-runtime',
  'frame-support/try-runtime',
  'cfg-types/try-runtime',
  'cfg-traits/try-runtime',
  'sp-runtime/try-runtime',
  'frame-system/try-runtime',
]
