[package]
authors = ['philip@centrifuge.io']
edition = '2018'
name = 'centrifuge-chain-runtime'
version = '2.0.0'

[features]
default = ['std']
no_std = []
std = [
    "app-crypto/std",
    'codec/std',
    'client/std',
    'rstd/std',
    'runtime-io/std',
    'support/std',
    'balances/std',
    'babe/std',
    'babe-primitives/std',
    'executive/std',
    'indices/std',
    'grandpa/std',
    'primitives/std',
    "session/std",
    'sr-primitives/std',
    'system/std',
    'timestamp/std',
    'sudo/std',
    'version/std',
    'serde',
    'safe-mix/std',
    'consensus-primitives/std',
    'offchain-primitives/std',
    'substrate-session/std',
]

[dependencies.app-crypto]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-application-crypto'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.babe]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-babe'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.babe-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-consensus-babe-primitives'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.balances]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-balances'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.client]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-client'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.consensus-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-consensus-common-primitives'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.executive]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-executive'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.grandpa]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-grandpa'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.indices]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-indices'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.session]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = "srml-session"
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.offchain-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-offchain-primitives'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.rstd]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-std'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.runtime-io]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-io'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.safe-mix]
default-features = false
version = '1.0'

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0'

[dependencies.sr-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.substrate-session]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.sudo]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-sudo'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-support'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-system'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.timestamp]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'srml-timestamp'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'

[dependencies.version]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-version'
rev = '4e1d637bf64e3437fa40f9e9e8460a5a0c0d9324'
[build-dependencies.wasm-builder-runner]
package = 'substrate-wasm-builder-runner'
version = '1.0.2'
