[package]
name = "centrifuge-chain-runtime"
version = "2.0.0"
authors = ["philip@centrifuge.io"]
edition = "2018"
build = "build.rs"
license = "LGPL-3.0"
homepage = "https://centrifuge.io/"
repository = "https://github.com/centrifuge/centrifuge-chain"

[dependencies]
# external pallet
substrate-pallet-multi-account = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate-pallet-multi-account", rev = "82505b7899595909bec2be0f1f4890b7a03b963c", default-features = false }
chainbridge = { version = "0.0.1", git = "https://github.com/vedhavyas/chainbridge-substrate.git", rev = "c38ea7b278d414bae4ee7f2e47ebded66811b9fd" , default-features = false}

# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
integer-sqrt = { version = "0.1.2" }
safe-mix = { version = "1.0", default-features = false }
smallvec = "1.4.0"
static_assertions = "1.1.0"
hex-literal = "0.2.1"
unique_assets = { git = "https://github.com/jaybutera/unique-assets", default-features = false , features = ["explicit-registries"]}

rustc-hex = { version = "2.0", optional = true }
serde = { version = "1.0.102", optional = true }

# primitives
sp-authority-discovery = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
sp-consensus-babe = { version = "0.8.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
sp-block-builder = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false}
sp-inherents = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
node-primitives = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
sp-offchain = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
sp-core = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
sp-io = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
sp-std = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
sp-api = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
sp-runtime = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
sp-staking = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
sp-session = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
sp-transaction-pool = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
sp-version = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
sp-arithmetic = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }

# frame dependencies
frame-benchmarking = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false, optional = true }
frame-executive = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
frame-support = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
frame-system = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
frame-system-rpc-runtime-api = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-authority-discovery = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-authorship = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-babe = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-balances = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-collective = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-democracy = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-elections-phragmen = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-finality-tracker = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-grandpa = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-im-online = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-indices = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-membership = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-offences = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-randomness-collective-flip = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-session = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false, features = ["historical"] }
pallet-staking = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-staking-reward-curve = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69"}
pallet-timestamp = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-utility = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-transaction-payment = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-identity = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }
pallet-scheduler = { version = "2.0.0-rc6", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69", default-features = false }

[build-dependencies]
wasm-builder-runner = { version = "1.0.5", package = "substrate-wasm-builder-runner", git = "https://github.com/centrifuge/substrate.git", rev = "7f5382862e1f47875f05a5e7ad6219d694ffbc69" }

[features]
default = ["std"]
std = [
    "unique_assets/std",
    "sp-authority-discovery/std",
    "pallet-authority-discovery/std",
    "pallet-authorship/std",
    "sp-consensus-babe/std",
    "pallet-babe/std",
    "pallet-balances/std",
    "sp-block-builder/std",
    "codec/std",
    "pallet-collective/std",
    "pallet-democracy/std",
    "pallet-elections-phragmen/std",
    "frame-executive/std",
    "pallet-finality-tracker/std",
    "pallet-grandpa/std",
    "pallet-im-online/std",
    "pallet-indices/std",
    "sp-inherents/std",
    "pallet-membership/std",
    "pallet-identity/std",
    "pallet-scheduler/std",
    "node-primitives/std",
    "sp-offchain/std",
    "pallet-offences/std",
    "sp-core/std",
    "pallet-randomness-collective-flip/std",
    "sp-std/std",
    "serde",
    "pallet-session/std",
    "sp-api/std",
    "sp-runtime/std",
    "sp-staking/std",
    "pallet-staking/std",
    "sp-session/std",
    "frame-benchmarking/std",
    "frame-support/std",
    "frame-system-rpc-runtime-api/std",
    "frame-system/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "pallet-transaction-payment/std",
    "sp-transaction-pool/std",
    "pallet-utility/std",
    "sp-version/std",
    "sp-arithmetic/std",
    "chainbridge/std",
    "substrate-pallet-multi-account/std",
    "sp-io/std",
    "rustc-hex",
    "safe-mix/std",
]
runtime-benchmarks = ["frame-benchmarking"]
