[package]
authors = ["Centrifuge <admin@centrifuge.io>"]
description = 'NFT Sales pallet'
edition = '2021'
license = "LGPL-3.0"
name = 'pallet-nft-sales'
repository = "https://github.com/centrifuge/centrifuge-chain/pallets/nft-sales"
version = '2.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = 'parity-scale-codec', version = '3.0.0', features = ['derive'] , default-features = false }
scale-info = { version = "2.0", default-features = false, features = ["derive"] }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.29" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.29" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.29" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.29" }

# Optional dependencies for benchmarking
frame-benchmarking = { git = "https://github.com/paritytech/substrate",  default-features = false , optional = true , branch = "polkadot-v0.9.29" }
pallet-balances = { git = "https://github.com/paritytech/substrate",  default-features = false , optional = true, branch = "polkadot-v0.9.29" }
pallet-uniques = { git = "https://github.com/paritytech/substrate",  default-features = false , optional = true, branch = "polkadot-v0.9.29" }
orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, optional = true, branch = "polkadot-v0.9.28" }
orml-traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, optional = true, branch = "polkadot-v0.9.28" }
cfg-types = { path = "../../libs/types", default-features = false, optional = true }
cfg-primitives = { path = "../../libs/primitives", default-features = false, optional = true }

[dev-dependencies]
# Substrate crates & pallets
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.29" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.29" }
pallet-balances = { git = "https://github.com/paritytech/substrate",  default-features = false , branch = "polkadot-v0.9.29" }
pallet-uniques = { git = "https://github.com/paritytech/substrate",  default-features = false , branch = "polkadot-v0.9.29" }

# Orml crates
orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = true, branch = "polkadot-v0.9.28" }
orml-traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library", default-features = false, branch = "polkadot-v0.9.28" }

# Local crates
cfg-primitives = { path = "../../libs/primitives", default-features = true }
cfg-types = { path = "../../libs/types", default-features = true}

[features]
default = ['std']
runtime-benchmarks = [
    "frame-benchmarking",
    "pallet-balances",
    "pallet-uniques",
    "cfg-types",
    "cfg-primitives",
    "orml-tokens",
    "orml-traits",
]
std = [
    'codec/std',
    'cfg-types/std',
    'frame-support/std',
    'frame-system/std',
    'sp-std/std',
    'sp-runtime/std',
    'orml-tokens/std',
    'orml-traits/std',
    'pallet-balances/std',
    'cfg-primitives/std',
]
