[package]
authors = ["Centrifuge <admin@centrifuge.io>"]
description = 'Loan pallet for runtime'
edition = '2018'
license = "LGPL-3.0"
name = 'pallet-loan'
repository = "https://github.com/centrifuge/centrifuge-chain/pallets/nav-feed"
version = '1.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
serde = { version = "1.0.102" }
codec = { package = 'parity-scale-codec', version = '2.0.0', features = ['derive'] , default-features = false }

frame-support = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
frame-system = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
sp-core = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
sp-runtime = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
sp-std = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
sp-arithmetic = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }

# optional dependencies for benchmarking
frame-benchmarking = { git = "https://github.com/centrifuge/substrate",  default-features = false , optional = true , branch = "master" }
pallet-balances = { git = "https://github.com/centrifuge/substrate",  default-features = false , optional = true, branch = "master" }
pallet-uniques = { git = "https://github.com/centrifuge/substrate",  default-features = false , optional = true, branch = "master" }
runtime-common = { path = "../../runtime/common", optional = true, default-features = false }
orml-tokens = { git = "https://github.com/centrifuge/open-runtime-module-library", default-features = false, optional = true, branch = "centrifuge" }
pallet-timestamp = { git = "https://github.com/centrifuge/substrate",  default-features = false, optional = true, branch = "master" }

# our pallets
common-traits = { path = "../../libs/common-traits", default-features = false}

[dev-dependencies]
sp-io = { git = "https://github.com/centrifuge/substrate", default-features = false , branch = "master" }
pallet-balances = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
runtime-common = { path = "../../runtime/common", default-features = false }
pallet-timestamp = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
orml-tokens = { git = "https://github.com/centrifuge/open-runtime-module-library", default-features = true, branch = "centrifuge" }
orml-traits = { git = "https://github.com/centrifuge/open-runtime-module-library", default-features = false, branch = "centrifuge" }
pallet-uniques = { git = "https://github.com/centrifuge/substrate",  default-features = false , branch = "master" }
pallet-tinlake-investor-pool = { path = "../tinlake-investor-pool", default-features = false}
primitives-tokens = { path = "../../primitives/tokens", default-features = false }

[features]
default = ['std']
runtime-benchmarks = [
    "frame-benchmarking",
    "pallet-balances",
    "pallet-uniques",
    "runtime-common",
    "orml-tokens",
    "pallet-timestamp"
]
std = [
    'serde/std',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-core/std',
    'sp-runtime/std',
    'sp-std/std',
    'sp-arithmetic/std',
    'common-traits/std',
]
