name: docker
on:
  push:
    branches: [main, 'release-v**']
  pull_request:
    paths: .github/workflow/docker.yml
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker Image tag'
        required: true
        default: ''
env:
  RUST_TOOLCHAIN: "nightly-2022-11-14"
jobs:
  docker:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        target: [ release, test ]
    runs-on: ${{ matrix.os }}
    env:
      WORKFLOW_TAG: ${{ github.event.inputs.docker_tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Free Space
        run: |
          echo "Listing 100 largest packages"
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
          df -h
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y --no-upgrade azure-cli google-cloud-sdk microsoft-edge-stable google-chrome-stable firefox powershell mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
          echo "Removing large directories"
          rm -rf /usr/share/dotnet/
          df -h
      - name: Set docker tag
        run: |
          if [ "${WORKFLOW_TAG}" != "" ]; then
            echo "DOCKER_TAG=${WORKFLOW_TAG}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
          fi
      - if: matrix.target == 'release'
        name: Build docker release
        run: docker build --build-arg RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN }} -t centrifugeio/centrifuge-chain:${{ env.DOCKER_TAG }}-latest .
      - if: matrix.target == 'test'
        name: Build docker test
        run: docker build --build-arg RUST_TOOLCHAIN=${{ env.RUST_TOOLCHAIN }} --build-arg OPTS="--features=fast-runtime" -t centrifugeio/centrifuge-chain:test-${{ env.DOCKER_TAG }}-latest .
      - name: Login to Docker Hub
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - if: matrix.target == 'release'
        name: Tag image release
        run: docker tag centrifugeio/centrifuge-chain:${{ env.DOCKER_TAG }}-latest "centrifugeio/centrifuge-chain:${{ env.DOCKER_TAG }}-$(date -u +%Y%m%d%H%M%S)-$(git rev-parse --short HEAD)"
      - if: matrix.target == 'test'
        name: Tag image test
        run: docker tag centrifugeio/centrifuge-chain:test-${{ env.DOCKER_TAG }}-latest "centrifugeio/centrifuge-chain:test-${{ env.DOCKER_TAG }}-$(date -u +%Y%m%d%H%M%S)-$(git rev-parse --short HEAD)"
      - name: List images
        run: docker images
      - name: Push image to Docker Hub
        run: docker push --all-tags --quiet centrifugeio/centrifuge-chain
